### ISSUE TITLE
The name of open tabs

### ISSUE THREAD

**Issue by apachexampp** [dockpanelsuite/dockpanelsuite#266]
I would like to access the elements in DockState.Document, so as to be able to read them (personally set) variables, but unfortunately I do not know how to do it.

**Comment by lextm** [comment]
The sample project shows how to access document items in `MainForm.CloseAllDocuments` method. With `IDockContent` at hand, you can later call `IDockContent.DockHandler.TabText` property to access the tab name. Of course, by casting `IDockContent` to the exact type you defined in your code, you can access other properties.

**Comment by Lailend** [comment]
Is it also somehow possible to check the already open panels docked to a side? (!DockState.Document). In my project I would like to open multiple Explorer windows for different projects. But It would be cool to check if this project is already open. 

The example app only checks for the DockState.Document forms.
Keeping track of the opened forms in a list isn't really a option out here because users can close the Explorer window.
Thnx!
