### ISSUE TITLE
Deep Copy of the Form

### ISSUE THREAD

**Issue by Nessi2410** [dockpanelsuite/dockpanelsuite#269]
Hello,

I am unable to copy the form which uses dockpanelsuite.
While Normal form i can copy.

Can you help me out.

Thanks in advance

**Comment by roken** [comment]
You'll need to provide some code to illustrate what you're trying to do and more description of what the actual problem is.  "Deep copy" is not a built-in feature in .NET or the DockPanel Suite, so I have no way to guess what isn't working with what you're attempting but I wouldn't expect there to be any limitations preventing you from performing a deep copy w/ the dockpanel.

**Comment by Nessi2410** [comment]
public object Clone() {

    BinaryFormatter formatter = new BinaryFormatter();
    MemoryStream stream = new MemoryStream();
    formatter.Serialize(stream, this);
    stream.Seek(0, SeekOrigin.Begin);

    return (MyForm) formatter.Deserialize(stream);

}

MyForm form2 = form1.Clone() as MyForm;

This code works for Other Forms but not for the form which uses Dockpanel dll.
Here i am trying to Clone one form to another.
Means it will copy all m parameters, design everything.

**Comment by lextm** [comment]
This probably won't be a feature we are going to add, but any pull request is welcome.
