### ISSUE TITLE
[mono] X11 Error encountered:  Error: BadMatch (invalid parameter attributes)

### ISSUE THREAD

**Issue by ArsenShnurkov** [dockpanelsuite/dockpanelsuite#273]
Mono claims to support WinForms 100%
http://www.mono-project.com/docs/gui/winforms/

DockPanelSuite is supported on mono (except drag & drop)
http://blog.lextudio.com/2012/02/dockpanel-suite-patch-to-support-lite-mode-on-mono/

I am trying to start <a href="https://github.com/dockpanelsuite/dockpanelsuite/blob/master/DockSample/DockSample.csproj">DockSample</a> project (on <a href="http://www.calculate-linux.org">Calculate Linux</a>), and perform some UI testing.
When I did testing, I got many exceptions similar to these:
<a href="https://gist.githubusercontent.com/ArsenShnurkov/e0d108140f8af8f19cb0/raw/5b23254c5e84b710a092a1092dda6f5f0d68be81/gistfile1.cs">gist.githubusercontent.com?id=...</a>
http://pastebin.mozilla-russia.org/111759

Probably related bugs:
https://github.com/dockpanelsuite/dockpanelsuite/issues/117 (won't fix, mono code to blame, without explaination)
https://github.com/dockpanelsuite/dockpanelsuite/issues/16 (refers to <a href="https://bugzilla.xamarin.com/show_bug.cgi?id=6176">bugzilla.xamarin.com?id=6176</a>, code of Control.Dispose() should check for cycling)

I am ready to recompile my local copy of mono, but don't know what to fix

**Comment by ArsenShnurkov** [comment]
for me it looks similar to 
https://github.com/dockpanelsuite/dockpanelsuite/issues/117
https://github.com/dockpanelsuite/dockpanelsuite/issues/16

I am ready to recompile my local copy of mone, but don't know what to fix

**Comment by lextm** [comment]
The debugging itself into such exceptions takes too much effort. If you set break points in both DPS and Mono WinForms, you should be able to observe that sometimes Mono's WinForms calculates some layout values to be negative and then crashes the app. That's why no detail was provided in #117, as I could not finish debugging nor locate the exact bug in Mono WinForms.

Mono's claim on WinForms 100% is a weak one, as there are many incompatibilities either undocumented nor reported (due to less interest to use Mono WinForms). I was toward promoting Mono WinForms a few years ago, but now tend to avoid it. You should switch to GTK# or MonoMac if you target a specific platform other than Windows.

I am not sure of @roken 's view on Mono support, but I personally mark that as obsolete, and I don't want to do any more attempt on that side.

**Comment by tokendroid** [comment]
Are there related bugs in mono bug tracker? Because we need a place to discuss them. IThere are many legacy WinForms applications, and they will not be rewritten with Gtk#

**Comment by ArsenShnurkov** [comment]
Are there related bugs in mono bug tracker? Because we need a place to discuss them. There are many legacy WinForms applications, and they will not be rewritten with Gtk#

Here is a new one:
https://bugzilla.xamarin.com/show_bug.cgi?id=26827

**Comment by roken** [comment]
With Microsoft's relatively recent formation of the .NET Foundation and open sourcing swaths of .NET I think the necessity to be able to support different runtime implementations and operating systems will only increase.  As I just mentioned in #274, there are a lot of aspects of the DPS that depend on Windows user32 calls which just aren't going to work out.  I haven't spent a lot of time looking at them, but my expectation is that in most of those situations the p/invoke was chosen over any existing method implemented in WinForms due to some issue with the WinForms implementation.

That all said, I'm not very well versed with the inner workings of WinForms on Mono, but some of the things I have seen have left me disappointed.  Not to say we shouldn't try to make DPS happy on Mono, I just don't see @lextm or myself being the ones to volunteer the time, and with a couple small exceptions, there hasn't been much interest from others to substantially contribute or collaborate on the project in general.

**Comment by DanWBR** [comment]
I've coded some workarounds so DockPanel could work fine on Mono. You can check my code at https://github.com/DanWBR/dwsim3/tree/master/DockPanelSuite.

To replace missing drag-and-drop funcionality for docking, I chose to add a drop-down menu for each window with a list of possible modes. You could add this menu directly in the DockPanel class too if you want.

**Comment by lextm** [comment]
@DanWBR Thanks for the info. I tried to take a look, but it seems that you did not fork this repo and then used it in your project as a submodule. Then it is quite difficult for me to dig what exactly are the changes you made. But since said above that I will not dig further, let's just leave it here for anyone else interested in Mono and hope they can contribute some new patches.

**Comment by DanWBR** [comment]
@lextm the main change I did was to remove the splitter dragging rectangle, because it was remaining on the screen even after dragging.

https://github.com/DanWBR/dwsim3/commit/6aa0a0bcf5ece83aaa4588796a01c391b540c308#diff-48eb9d1184a810a0dff551e0563a3292

I also removed some rotation instructions because System.Drawing on Mono doesn't support matrix transformations.

https://github.com/DanWBR/dwsim3/commit/6aa0a0bcf5ece83aaa4588796a01c391b540c308#diff-48eb9d1184a810a0dff551e0563a3292

**Comment by DanWBR** [comment]
Also, issue https://github.com/dockpanelsuite/dockpanelsuite/issues/117 seems to be fixed in the latest Mono version. If not, I can take a look at it and see what can be done.
