### ISSUE TITLE
How to edit Window List Items (on tabs section)

### ISSUE THREAD

**Issue by zzz77** [dockpanelsuite/dockpanelsuite#275]
Good morning!

How can I edit items of Window List:
![windowlistitems](https://cloud.githubusercontent.com/assets/3635408/6244868/a3d9869a-b769-11e4-865c-a1e473460403.png)
I would like to have list of only non-visible tabs (I mean tabs which are opened, but which are not shown because panel is overflowed) in this DropDownList. I would like to see only TestForm4, TestForm5, TestForm6:
![windowlistitems2](https://cloud.githubusercontent.com/assets/3635408/6244875/a8a120f2-b769-11e4-8451-43ddcea37b31.png)
How can I do it?

Thanks for your time
Mikhail

**Comment by lextm** [comment]
This is more of a feature request. But I am not quite interested in it, because VS always show all tabs (visible or not does not matter). There is no real benefit to change this behavior.

But if you do want to customize the behavior, you can do so by creating your own DPS theme and then modify your dock pane strip derived from `DockPaneStripBase` class.

You can see from [the VS2005 version](https://github.com/dockpanelsuite/dockpanelsuite/blob/master/WinFormsUI/Docking/VS2005DockPaneStrip.cs) that in `WindowList_Click` method how add tabs are added to the list. The filtering can be added there to remove visible tabs.

If you don't know which tabs are visible, you can always resort to methods such as `DrawTabStrip_Document` which shows exactly how to determine which tabs are visible to be drawn out.

**Comment by zzz77** [comment]
Ok, thanks for help!
