### ISSUE TITLE
How to dock open Forms vertically or horizontally 

### ISSUE THREAD

**Issue by Nessi2410** [dockpanelsuite/dockpanelsuite#279]
Hello,

I want all the forms auto dock vertically or horizontally on a click of one button.

Regards.

**Comment by roken** [comment]
I find myself conflicted because I strongly desire and encourage questions because that is what helps form a community around this project, but at the risk of coming across as rude, please read the following:  http://mattgemmell.com/what-have-you-tried/

People will be happy to discuss problems or specific technical issues you encounter, but they should be targeted and detailed.  This is written like a requirement handed to you by your manager.

**Comment by Nessi2410** [comment]
My apologies

I am able dock the forms horizontally . But the docked forms should be of same size i.e according to the panel size. Please refer the following image as an eg.
![image](https://cloud.githubusercontent.com/assets/8386205/6386493/5f7062c6-bd9f-11e4-878a-d5bc42bd322c.png)

**Comment by Huntk23** [comment]
Hi Nessi2410,

Sorry for the long response as I only try to help the guys out who still manage this awesome control by answering questions. Hopefully you are still watching this thread or anyone else who was not able to figure this out.

To get the effect you are trying to attain in Alpha8 3.0 (version I use) you can do this:

```c#
int dockWidth = dockPanel.Size.Width/3;

form1.Show(dockPanel, DockState.DockLeft);
dockPanel.DockLeftPortion = dockWidth;

form2.Show(dockPanel, DockState.Document);

form3.Show(dockPanel, DockState.DockRight);
dockPanel.DockRightPortion = dockWidth;
```

This should give the desired effect you are after.

**Comment by Nessi2410** [comment]
Thank u for your response.. You are genius :)
