### ISSUE TITLE
Hide on close and OnFormClosing

### ISSUE THREAD

**Issue by siemandelc** [dockpanelsuite/dockpanelsuite#281]
Hi,

I want to prompt a dialog when the "close button" is pressed on a DockContent form with "HideOnClose" enabled. I've tried all the common solutions and I just can't get it to work. Is this even possible? I feel like it is because either I'm missing something stupidly obvious or it's just hard to do!

**Comment by Huntk23** [comment]
You can either do the following in the FormClosing event subscription:

```c#
DialogResult dialogResult = MessageBox.Show("Would you like to hide this window?", "Oops!", MessageBoxButtons.YesNoCancel);

if (dialogResult == DialogResult.Yes)
{
    HideOnClose = true;
    Close();
}
else if (dialogResult == DialogResult.No)
{
    Close();
}
else
{
    formClosingEventArgs.Cancel = true;
}
```

Or you have to subscribe to the VisibleChanged  event. The DockHandler basically checks when the the HideOnClose property in a closing method and simple hides the window like form.Hide() instead of letting it close.

Note that VisibleChanged is more than the Hide() method being called so you will have to handle that.
