### ISSUE TITLE
Icon Drawing Fuzzy

### ISSUE THREAD

**Issue by ChrisCollins8** [dockpanelsuite/dockpanelsuite#284]
Hi,

I noticed that the icon drawing seems to be kind of fuzzy. I was able to improve the quality of the icon drawing on the tabs/windows/etc by switching it from DrawIcon to DrawImage and using the Icon.ToBitmap() method. If the icons are set to 32x32 they seem to draw well but 16x16 came out fuzzy. 

I will note I haven't really checked to see if there are any performance implications to this and I also haven't tested it using Windows 8/etc. As of right now I have only seen it on windows 7 but I figured it was worth a note.

**Comment by lextm** [comment]
I think more information (such as screen shots) is required, as below
* About the icon file, what sizes of images does it contain? That heavily influences which size is chosen at runtime for rendering.
* When you describe the runtime effect is fuzzy, what exactly is the pattern? That often can lead us to the cause.

**Comment by lextm** [comment]
Thanks. I will do some further analysis on this issue. By enlarging them to 800% I can see the actual pixels being rendered are significantly different, meaning there must be some processing in the background, which were not fully documented by Microsoft in the obvious MSDN links.

**Comment by lextm** [comment]
I have done a few experiments, and it seems to be an issue of `System.Drawing`.

1. When an icon with multiple image types (16x16, 32x32, and so on), `Graphics.DrawIcon` does not seem to pick up the 16x16 size. Thus, the chosen size (32x32 in my test) is scaled down to 16x16 and lead to not only the fuzzy result but also some further detail loss. The detail loss can be observed by setting the same icon as main form icon. Then the icon in window title bar looks different from the document tab icon, though they come from the same icon file.

1. When an icon with only 16x16 image type, `Graphics.DrawIcon` seems to give the same look of the window title bar (still fuzzy, but no further loss). I think that's already the best we can achieve.

1. `Graphics.DrawImage` with `Icon.ToBitmap` as you suggested does not give a better result than the simple workaround above, and it also requires code changes (which I personally try to avoid).

Thus, my conclusion is that instead of using an icon with multiple image types, we should use an icon with only 16x16 image type. In this way, no code change to DPS is required.

**Comment by ChrisCollins8** [comment]
While I agree using a 16x16 icon does achieve the desired result the app in question is grabbing the icon from the filename so the icon associated with the extension of the file it is loading. As such I have no control over the icon format available and it appears that the ToBitmap does get the desired result of forcing it into drawing the properly sized icon instead of a set 32x32 icon.

**Comment by lextm** [comment]
As this is more of a `System.Drawing` and GDI+ issue, it would be less relevant for DPS to fix it.

Meanwhile, for any apps built upon DPS, the control over icon format should be required. If the icon is provided by end users who customize the look and feel, a message should be delivered to such users that only icons follow the mandate format are supported.
