### ISSUE TITLE
Form_Load event does not trigger

### ISSUE THREAD

**Issue by rqx110** [dockpanelsuite/dockpanelsuite#293]
If set the ShowHint to *AutoHide, the Form_Load event does not trigger.

**Comment by lextm** [comment]
You provided too little information and it is possible to reproduce.

**Comment by rqx110** [comment]
在demoSample的DummyToolbox中添加Private void DummyToolbox_Load(object sender, EventArgs e)事件，因为其在启动时默认是隐藏的，这个事件并不会触发，只有当鼠标移动过去让其显示时，该事件才会被触发。但我用以前旧版本的时候并没有该问题。所有我不清楚是新版设计成这样，还是是一个bug。

**Comment by lextm** [comment]
The proper steps to reproduce are,

1. Open DemoSample project and add a Load event handler to DummyToolbox. In the event handler, simply show a message dialog.
1. Compile this project and also delete any previously saved layout config file.
1. Execute the sample, and click View | Toolbox menu item.

Then this panel shows as hidden. Place the cursor on its strip bar and the message dialog shows. After that the panel shows.

The question is whether this behavior is by design.

I think it is by design, and it is not a bug.

**Comment by roken** [comment]
This is the expected behavior for a WinForms Form.  The Load event fires sometime before it is made visible for the first time, so if it starts out hidden, the form will not "load" until forced to display.

Depending on what you're trying to accomplish, there are many other events available that may be more useful for your use case.
