### ISSUE TITLE
Complete the missing pieces in VS 2013 blue theme

### ISSUE THREAD

**Issue by lextm** [dockpanelsuite/dockpanelsuite#316]
In #306 a few missing elements were pointed out. This issue is created to track future work on this theme.

- [x] Dock indicator is missing
- [x] The 1-pixel thin border of dock pane is missing
- [x] Other elements
- [x] Tool window tab is rendered differently. VS uses border lines instead of separators.
- [x] Change theme base from VS2012 Light to VS2012 Blue.

**Comment by lextm** [comment]
@thijse if you are interested in contributing again, you might grab this.

**Comment by astrohart** [comment]
@thijse Yes please that would be a correct, if you could please fix the Blue Theme.  It's my favorite and I am not enough of a DockPanel expert to know how to get it right.  :-)

I am trying to do Winforms because, personally, I think WPF is harder to code in.  I like using the Windows Forms Designer to drag stuff around on my screen :-) and double click on things.  It's more fun.  The WPF designer feels more like developing a Web page and I am not a Web developer.

**Comment by lextm** [comment]
It is recommended that users use VS2012 Blue theme in #378.

The new palette based theming breaks this VS2013 theme, and in the meantime reveals more gaps in this approach,

- [ ] Tool window tab is rendered differently. It uses border lines instead of separators.

Will finish other refactoring such as #376 and then revisit this one.

**Comment by lextm** [comment]
Done in master branch.
