### ISSUE TITLE
VS 2012 dark theme is being worked on

### ISSUE THREAD

**Issue by lextm** [dockpanelsuite/dockpanelsuite#317]
Some guys seem to have been working on a dark theme already,

https://github.com/armano2/dockpanelsuite

@roken we might evaluate its completeness in the future.

**Comment by lextm** [comment]
Another dark theme is here,

https://github.com/RyuuKitsune/dockpanelsuite/

**Comment by lextm** [comment]
@armono2 and @RyuuKitsune if you would like to contribute a dark theme, you might join force instead of working on this separately.

**Comment by DanielMPries** [comment]
I made a VS2012 dark version last year for a project I was working on.  I'll have to check first if its compatible with the latest build and then I'll pass it along.

**Comment by lextm** [comment]
@DanielMPries PR is welcome. Thanks. 

Due to the architectural changes introduced for 2.10 release, all themes are now individual assemblies. It should not be too difficult to adapt to the changes if you check out existing themes, such as the 2012 light theme.

**Comment by DanielMPries** [comment]
Yes, I see that.  In trying to incorporate my changes, I see 2 main challenges. 1. The theme style needs some seperation from the theme colors and 2. The theme coloring implemenation is not granular enough.  For example, the AutoHideStrip shares colors for the rectangle tab and the text.  Before I do a pull request, I'm trying to see if I can seperate color implementation so that we can use styles from the Microsoft provided [Visual Studio Color Theme Editor](https://visualstudiogallery.msdn.microsoft.com/366ad100-0003-4c9a-81a8-337d4e7ace05).  That way UI themes and thier components, and color schemes within that UI theme are essentially 2 seperate concerns.  Then the concept of a "dark" theme is a matter of appling a color palette to a VS2020 theme.  That said, I don't intend on implementing every color provided by the Color Theme Editor but I do think its simple enough to implement some of it and allow it to be derived from the file that the extension provides.  

When all of it is in a working state, I'll submit a PR and get it incorporated.

**Comment by lextm** [comment]
@DanielMPries I think the points you listed are the limitations we know from the `DockPanelSkin` design. This class was designed for VS 2003/2005 themes, so it does not work well with VS 2012/2013 new themes.

To make things worse, when I ported in the VS 2012 light theme, I set the different colors almost randomly in the skin properties, and then used them in different element rendering. That was the quickest way to port that theme, but it added complexity to the equation and I can now see the VS2013 blue theme (in #316) the issue remains.

Your suggestion on building a standard color palette is great. If you can create a new class `DockPanelColorPalette` and make it a property of `ThemeBase`, then each themes can have its own palette. For each dock panel elements that wants to read the palette, we can expose the color palette in the same way of the current skin. So finally we have old themes who use skins, while new themes use color palettes.

That should heavily simplify the way new themes are developed.

**Comment by lextm** [comment]
There comes another dark theme, https://github.com/srober12/dockpanelsuite

**Comment by lextm** [comment]
@DanielMPries as I am now working on #374, I have now added an experimental VS2012 Dark theme in dcb48ed5f37dc6fedc8af6734350f7cd8357fb8b

It is still half-baked, as the palette does not work quite well with the icons/images. I still need more time to finish it.

**Comment by lextm** [comment]
Close this as #377 provides a better approach.
