### ISSUE TITLE
Scaling on high resolution screens

### ISSUE THREAD

**Issue by pakhack** [dockpanelsuite/dockpanelsuite#330]
I have a problem with the dockpanel scaling on a 120 DPI screen, when the scaling level is set to 125%. The problem is that the docked forms on the bottom and right disappear when scaling is set to 125%. I attach images demonstrating the problem.

125%
![125](https://cloud.githubusercontent.com/assets/9501150/11629815/fea19eb2-9d02-11e5-9c09-7a47fbfe5054.PNG)

100%
![100](https://cloud.githubusercontent.com/assets/9501150/11629816/fea4ce8e-9d02-11e5-9004-ee0ad72a35cb.PNG)

Any ideas?

**Comment by lextm** [comment]
I have tested using the sample project on a Windows 10 machine (virtual machine running in Parallels) with .NET 4.6.1, but even when I set scaling to 125% the autohide tabs are still OK.

Can you do more testing on your side? DPI support in .NET comes pretty late, and I believe many rendering bugs are only fixed in 4.5/4.6.

It would be pretty difficult for DPS to work around .NET bugs, but we welcome pull requests. Thanks.

**Comment by bkbartk** [comment]
Hi pakhack,

This is probably not the place to ask but I don't know where I can pop this question else
how do you make those subtabs within the maintabs?
