### ISSUE TITLE
Creating Workspace in Dockpanel

### ISSUE THREAD

**Issue by Nessi2410** [dockpanelsuite/dockpanelsuite#416]
Hello,

please refer the image for requirement.
I want to create numerous workspaces in my project. and Forms to be docked inside each workspace(document).
Can you help me with that?? 
![eg](https://cloud.githubusercontent.com/assets/8386205/18738435/5d39b3ac-80b9-11e6-9466-a0c5e599fdb9.png)

**Comment by lextm** [comment]
DockPanel Suite might not be the solution you are looking for.

https://docs.dockpanelsuite.com/en/latest/themes/basics.html#visual-elements-of-a-theme

The basic visual elements are dock panes which host one or more dock contents, and panes have their captions and strips.

So if you do want four forms without captions/strips, you have to develop your own control or use another control library.

**Comment by Nessi2410** [comment]
Let the forms have caption but inside the workspace..

**Comment by lextm** [comment]
Then it is duplicate to #373 . You can check how the sample project sets its layout by code, in `MainForm.menuItemLayoutByCode_Click`. Slight modification to that can achieve what you need.

**Comment by Nessi2410** [comment]
No its not a duplicate. Everybody can have a caption but it should be enclosed under One tab, Other Tabs will have its own Forms.

**Comment by lextm** [comment]
You have to learn "the DockPanel Suite terms", such as panes/documents/tool windows. Otherwise, terms such as "forms" have no meaning at all in the discussion.

The "workspace tab" in your scenario cannot be converted to a valid DPS item. You probably should use a tab control as outer control, and then in each tab page place a `DockPanel` control to host inner dock panes.

In all, my opinion is that DPS is not the solution for your problem, and you should find something else.

**Comment by Nessi2410** [comment]
Hello Lex,

It was a good suggestion for usage of tabpages. But when i do so documentating the form makes it blank.
