### ISSUE TITLE
Add option to disable double-click creating a floating window. 

### ISSUE THREAD

**Issue by jakehedlund** [dockpanelsuite/dockpanelsuite#546]
A computer-challenged customer is having difficulties accidentally double-clicking the dockpanel tabs which causes them to undock and turn into a floating window. This can be a problem when not expecting it. Setting the DockAreas property is not sufficient as the ability to undock is still desired - just not when double-clicked. 

Option added in `DockPanel.cs`:  

```c#
        private bool m_floatOnDoubleClick;
        [LocalizedCategory("Category_Docking")]
        [LocalizedDescription("DockPanel_FloatOnDoubleClick_Description")]
        [DefaultValue(true)]
        public bool AllowFloatOnDoubleClick
        {
            get
            {
                return m_floatOnDoubleClick;
            }
            set
            {
                m_floatOnDoubleClick = value;
            }
        }
```

Option checked in `DockPaneStripBase.cs`: 

```c#
        [SecurityPermission(SecurityAction.LinkDemand, Flags = SecurityPermissionFlag.UnmanagedCode)]
        protected override void WndProc(ref Message m)
        {
            if (m.Msg == (int)Win32.Msgs.WM_LBUTTONDBLCLK)
            {
                base.WndProc(ref m);

                int index = HitTest();
                if (DockPane.DockPanel.AllowEndUserDocking && DockPane.DockPanel.AllowFloatOnDoubleClick && index != -1)
                {
                    IDockContent content = Tabs[index].Content;
                    if (content.DockHandler.CheckDockState(!content.DockHandler.IsFloat) != DockState.Unknown)
                        content.DockHandler.IsFloat = !content.DockHandler.IsFloat;	
                }

                return;
            }

            base.WndProc(ref m);
            return;
        }

```

Help text added in `Strings.resx`: `DockPanel_FloatOnDoubleClick_Description	Allow document to float (undock) when tab is double-clicked.`

**Comment by lextm** [comment]
You should be able create your own themes and then override `WndProc` in the strip class to disable the behavior like you indicated above. I don't think a change in DockPanel Suite itself is needed and it brings no real value to most users, who should expect DPS to behave like VS.

**Comment by jakehedlund** [comment]
Thanks for the tip. The intent was to create a theme-independent option for
those who want it. I agree that it's a very narrow use case, but I figured
it could be useful to someone who doesn't want to go to the trouble of
creating a custom theme.

**Comment by lextm** [comment]
The current bar to include some feature in DockPanel Suite is higher than ever, as maintainers do have quite limited time to review the changes. Many pull requests are pending due to the same reason.

If something can be easily implemented in a custom theme, then you are not bind to DPS itself and can do whatever changes you like.

**Comment by jakehedlund** [comment]
Totally understand, that's why I made the three-line addition and submitted
it instead of just suggesting the feature.

This option would also provide the inverse option that the FloatWindow
class already has:

private bool m_doubleClickTitleBarToDock = true;
        public bool DoubleClickTitleBarToDock
        {
            get { return m_doubleClickTitleBarToDock; }
            set { m_doubleClickTitleBarToDock = value; }
        }

Anyway, I do like DockPanelSuite and how feature-rich it is. Keep up the
good work.

**Comment by DanCarterGMSL** [comment]
I think this issue should be considered for inclusion for the following reasons:

- Double-clicking a tab in Visual Studio 2017 does not float the window. This suggests that this should at least be an option.
- This issue has a duplicate at #156, which seems to suggest that this feature is actually desired by the DockPanelSuite community.
- Some users have reported a bug involving double clicking that I have opened as issue #584. For this reason I would like to disable the feature that double-clicking a tab makes it float to prevent this bug being a problem for our users.
- (Mentioned by @jakehedlund): There is an equivalent property on `FloatWindow`. If double-clicking a `FloatWindow` does not "un-float" the window, but double-clicking a tab floats it, that seems inconsistent.

**Comment by lextm** [comment]
Instead of making it "an option", I think it should be made a separate theme. Related to #506 and #577.

#584 will be investigated separating.

`FloatWindow` is far from feature complete (also related to #506), so "double clicing a `FloatWindow` does not unfloat the window" should be handled as a separate issue too.

**Comment by jakehedlund** [comment]
Why don't we take a vote? You can drag the panel to float it anyway, why do
you need to double-click it too? Seems redundant enough to at least make it
optional.

**Comment by lextm** [comment]
@jakehedlund that's a behavior defined by Microsoft for certain VS releases, and the goal of this library is to emulate the same.

For a project with very limited resource (volunteer hours from me mainly in the past few years), it is not fair to "take a vote". Adding a switch/flag might seem to be a "simple" thing in your eye, but once added it is part of a contract to be maintained. That's why I said above it would be preferred to be isolated to a VS2017/2019 theme, as that minimizes the impact to only whoever uses that theme(s) and I don't need to spend time asking inquiries like this one.

Of course, if we get more resources to work on this project, things can change.

**Comment by DanCarterGMSL** [comment]
I've just tried the double-clicking behaviour in VS 2015, and it doesn't undock a document. Perhaps this suggests that the VS2015 themes should be changed, so that double-clicking a tab does not undock the document?
