### ISSUE TITLE
NU1108 Cycle Dependency in .NET Core 3.1

### ISSUE THREAD

**Issue by stefannikolei** [dockpanelsuite/dockpanelsuite#642]
When trying to add the package to an .NET Core 3.1 App you will end up with an Cycle.

The problems seems to be this section in the generated nuspec:

```
<dependencies>
      <group targetFramework=".NETFramework3.5">
        <dependency id="DockPanelSuite" version="3.1.0-beta6" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETFramework4.0">
        <dependency id="DockPanelSuite" version="3.1.0-beta6" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETCoreApp3.1">
        <dependency id="DockPanelSuite" version="3.1.0-beta6" exclude="Build,Analyzers" />
      </group>
    </dependencies>

```
when it is changed to this it will work

```
    <dependencies>
      <group targetFramework=".NETFramework3.5" />
      <group targetFramework=".NETFramework4.0" />
      <group targetFramework=".NETCoreApp3.1" />
    </dependencies>
```
I could acomplish that by closing all other projects while generating the package. This can not be the solution. But perhaps a hint to start. I narrowed it down to the Themes. Closing all of them will generate a "good" package

And here a picture from Dotpeek

![image](https://user-images.githubusercontent.com/873751/102265082-d62c7400-3f16-11eb-9d46-48a1b3d4e0a0.png)

**Comment by scottstephens** [comment]
I found a more palatable workaround for this issue:
1. Open the Tools->Options settings page.
2. Go to the Nuget Package Manager->General section
3. Under Package Management, change the "Default package management format" to "PackageReference"

Still kind of sucks as this is a global settings change.

You can learn a little more about this issue here:

- https://github.com/NuGet/Home/issues/5751
- https://stackoverflow.com/questions/48878418/circular-dependency-detected-when-installing-nuget-package-akavache-6-0-0-alpha

**Comment by lextm** [comment]
Duplicate to #616
